pandoc -s -o calculus.docx calculus.md
pandoc -s -o cnn.docx cnn.md
pandoc -s -o gilbert.docx gilbert.md
pandoc -s -o goodFellow4.docx goodFellow4.md
pandoc -s -o goodFellow5.docx goodFellow5.md
pandoc -s -o goodFellow6.docx goodFellow6.md
pandoc -s -o goodFellow7.docx goodFellow7.md
pandoc -s -o goodFellow8.docx goodFellow8.md
pandoc -s -o goodFellow9.docx goodFellow9.md
pandoc -s -o index.docx index.md
pandoc -s -o inference.docx inference.md
pandoc -s -o manifold.docx manifold.md
pandoc -s -o spectral.docx spectral.md
