site_name: My notes
site_description: Everything I Read
site_author: Mastan
pages:
    - Home : 'index.md'
    - Linear Algebra and Differential Eq. : gilbert.md
    - Calculus : calculus.md
    - ManifoldBasics : manifold.md    
    - Numerical Computation 4: goodFellow4.md
    - Machine learning Basics 5: goodFellow5.md
    - Inference : inference.md
    - Deep Feedfroward networks 6: goodFellow6.md
    - Regularization 7: goodFellow7.md
    - Optimization for Deep-models 8: goodFellow8.md
    - Convolutional Network 9: goodFellow9.md
    - SpectralClustering : spectral.md
    - GAN : gan.md

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list
    - pymdownx.arithmatex
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde    
    - pymdownx.arithmatex:
        generic: true
      
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css: [docskimmer.css]

theme: readthedocs
